/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("org.yaml:snakeyaml:1.30")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.8.2")
    compileOnly("net.kyori:adventure-api:4.9.3")
    compileOnly("com.github.siroshun09.configapi:configapi:4.6.0")
    compileOnly("com.github.siroshun09.configapi:configapi-yaml:4.6.0")
    compileOnly("org.jetbrains:annotations:23.0.0")
}

group = "com.github.siroshun09.translationloader"
version = "2.0.2"
description = "TranslationLoader"
java.sourceCompatibility = JavaVersion.VERSION_11

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
