name: Java CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew build
      - name: Move the artifact
        run: |
          mkdir staging
          mv build staging/parent
          mv api/build staging/api
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        continue-on-error: true
        with:
          name: Package
          path: staging
