name: Deploy Javadoc to GitHub Pages (Gradle)
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew aggregateJavadoc
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/aggregateJavadoc
          allow_empty_commit: true
